### ISSUE TITLE
fix dependency issues with nimbus-jose-jwt

### ISSUE THREAD

**Issue by tommytroen** [navikt/mock-oauth2-server#27]
Multiple versions of `nimbus-jose-jwt` on classpath may lead to exceptions such as: 
`NoSuchMethodError: com.nimbusds.jose.jwk.JWKSet.toJSONObject()Lnet/minidev/json/JSONObject;`

Read more:
https://connect2id.com/blog/nimbus-jose-jwt-9

Remove dependency on stuff from net.minidev:json-smart etc

More details on related exceptions:
https://nav-it.slack.com/archives/C60FFACN5/p1599489125306800

**Comment by tommytroen** [comment]
shouldn´t be an issue after upgrading to 9.x
